#! /bin/bash

VERSION="latest"

docker create \
 --name=s4t_designate \
 --restart unless-stopped\
 --network=s4t-controller-network \
 --hostname designate \
 -p 9002:9001 \
 -p 53:53/udp \
 -p 53:53/tcp \
 -v s4t_designate_config:/etc/designate/ \
 -v /var/log/designate-conductor:/var/log/designate \
smartme/s4t_designate:$VERSION

docker cp conf/designate.conf s4t_designate:/etc/designate/
docker cp conf/pools.yaml s4t_designate:/etc/designate/
docker cp conf/named.conf.options  s4t_designate:/etc/bind/

docker run --rm \
 --network=s4t-controller-network \
 -v s4t_designate_config:/etc/designate/ \
 -v /var/log/designate-conductor:/var/log/designate \
smartme/s4t_designate:$VERSION \
/bin/sh -c "chown -R designate:designate /var/log/designate/" 

docker run --rm \
 --network=s4t-controller-network \
 -v s4t_designate_config:/etc/designate/ \
 -v /var/log/designate-conductor:/var/log/designate \
smartme/s4t_designate:$VERSION /bin/sh -c "designate-manage database sync" designate

docker run --rm \
 --network=s4t-controller-network \
 -v s4t_designate_config:/etc/designate/ \
 -v /var/log/designate-conductor:/var/log/designate \
smartme/s4t_designate:$VERSION /bin/sh -c "designate-manage pool update" designate

docker cp  build/bin/startDesignate s4t_designate:/usr/local/bin/
 
docker start s4t_designate
