version: '3.7'
services:
  crossbario:
    container_name: s4t_iotronic_crossbar
    restart: unless-stopped
    image: smartmeio/s4t_iotronic_crossbar:latest
    volumes:
      - 's4t_crossbar_config:/node/.crossbar'
      - /etc/ssl/iotronic/client_iotronic/:/node/.crossbar/ssl:ro
    network_mode: host

  wstun:
    container_name: s4t_iotronic_wstun
    restart: unless-stopped
    image: smartmeio/s4t_iotronic_wstun:1.1.0
    volumes:
      - '/etc/ssl/iotronic/client_iotronic:/var/lib/iotronic/ssl/:ro'
      - 's4t_iotronic_wagent_wstun:/var/lib/wstun:ro'
    network_mode: host

  wagent:
    container_name: s4t_iotronic_wagent
    image: smartmeio/s4t_iotronic_wagent:smartme-test
    restart: unless-stopped
    hostname: wagent1
    volumes:
      - 's4t_iotronic_wagent_config:/etc/iotronic/'
      - 's4t_iotronic_wagent_nginx:/etc/nginx/'
      - 's4t_iotronic_wagent_wstun:/var/lib/wstun'
      - '/var/log/iotronic-wagent:/var/log/iotronic'
    network_mode: host

volumes:
  s4t_crossbar_config:
    name: s4t_crossbar_config
  s4t_iotronic_db_data:
    name: s4t_iotronic_db_data
  s4t_iotronic_db_config:
    name: s4t_iotronic_db_config
  s4t_iotronic_wagent_config:
    name: s4t_iotronic_wagent_config
  s4t_iotronic_wagent_nginx:
    name: s4t_iotronic_wagent_nginx
  s4t_iotronic_ui_config:
    name: s4t_iotronic_ui_config
  s4t_iotronic_wagent_wstun:
    name: s4t_iotronic_wagent_wstun

networks:
  default:
    name: smartme-wagent-network
    driver: 'bridge'
