#! /bin/bash

VERSION=allowlist
CERT_PATH="/etc/ssl/iotronic/client_iotronic/"

ALLOW_PATH="/var/lib/docker/volumes/felooca_test_iotronic_wagent_config/_data/allowlist"

docker build -t smartmeio/smartmeio_test_iotronic_wstun:$VERSION .

RANGE="50000-50100:50000-50100"

docker run -d \
 --name=smartmeio_test_iotronic_wstun \
 --network=host \
 --restart unless-stopped\
 -p 8080:8080 \
 -p $RANGE \
-v $CERT_PATH:/var/lib/iotronic/ssl/:ro \
-v $ALLOW_PATH:/var/lib/wstun/allowlist:ro \
smartmeio/smartmeio_test_iotronic_wstun:$VERSION