#! /bin/bash

CERT_PATH="/etc/ssl/iotronic/client_iotronic/"

docker create \
 --name=felooca_test_iotronic_crossbar \
 --network=host \
 --restart unless-stopped\
 -p 8181:8181 \
 -v felooca_test_crossbar_config:/node/.crossbar \
 -v $CERT_PATH:/node/.crossbar/ssl:ro \
crossbario/crossbar:cpy3-20.2.1


docker cp confs/config.json felooca_test_iotronic_crossbar:/node/.crossbar/

docker start felooca_test_iotronic_crossbar
