#! /bin/bash

VERSION="latest"
docker create \
 --name=smartme_test_iotronic_ui \
 --restart unless-stopped\
 --network=smartme_test_network \
 -p 8585:80 \
 -v smartme_test_iotronic_ui_config:/etc/openstack-dashboard/ \
 -v /var/log/iotronic-ui:/var/log/apache2/ \
smartme/smartme_test_iotronic_ui:$VERSION

docker cp conf/local_settings.py smartme_test_iotronic_ui:/etc/openstack-dashboard

docker start smartme_test_iotronic_ui